---
title: Get common IDs across datasets
output:
  html_document: default
---

We'll get a set of common IDs from the three databases (covariates, genotypes, facial morphology), after cleaning them.
We'll keep only those IDs in the set of common IDs in the main analysis.

## Preliminares

Loading libraries

```{r libraries}
library(tidyverse)
```

Setting folders, and loading databases, getting common set of IDs and saving object

```{r databases, warning=FALSE}
setwd('..')
path <- getwd()

#Reading covariates
setwd(paste(path, "/DataBases", sep = ""))
covs <- read_csv("Covariates.csv", col_types = cols(ID = col_character() ) )
#Remove NAs in covs
covs <- na.omit(covs)
#Keep only Male/Female individuals
covs <- covs %>% filter(Sex == "Female" | Sex == "Male")

#Reading face shape and genotype IDs
setwd(paste(path, "/DataBases/IDS", sep = ""))

faceIDs <- read_csv("total_faceshape_ids.txt", col_names = F, col_types = cols(X1 = col_character()))
genoIDs <- read_csv("total_genotype_ids.txt", col_names = F, col_types = cols(X1 = col_character()))

common_ids <- intersect(intersect(faceIDs$X1, na.omit(covs)$ID ), genoIDs$X1)
write_csv(as.data.frame(common_ids), paste(path, "/Results/common_ids.txt", sep = ""), col_names = FALSE)
```

## Session information

```{r}
sessionInfo()
```

